-- Inserting into the Ingredients table
INSERT INTO Ingredients (IngredientName) VALUES
('Flour'),
('Sugar'),
('Eggs'),
('Milk'),
('Butter'),
('Chicken Breast'),
('Olive Oil'),
('Garlic'),
('Salt'),
('Pepper'),
('Pasta'),
('Tomato Sauce'),
('Cheese'),
('Bread'),
('Bacon'),
('Lettuce'),
('Mayonnaise'),
('Beef'),
('Onion'),
('Rice');

-- Inserting into the Meals table
INSERT INTO Meals (MealName, MealRecipe, MealPicture) VALUES
('Chocolate Cake', 'Mix flour, sugar, and eggs. Bake in the oven.', '/images/chocolate_cake.jpg'),
('Spaghetti Carbonara', 'Cook pasta. Mix with bacon and cheese.', '/images/spaghetti_carbonara.jpg'),
('Caesar Salad', 'Mix lettuce with Caesar dressing and croutons.', '/images/caesar_salad.jpg'),
('Grilled Chicken', 'Grill chicken breasts with spices.', '/images/grilled_chicken.jpg'),
('Beef Stew', 'Cook beef with vegetables and broth.', '/images/beef_stew.jpg'),
('Garlic Bread', 'Spread garlic butter on bread and bake.', '/images/garlic_bread.jpg'),
('Chicken Alfredo', 'Cook pasta and mix with Alfredo sauce and chicken.', '/images/chicken_alfredo.jpg'),
('BLT Sandwich', 'Make sandwich with bacon, lettuce, and tomato.', '/images/blt_sandwich.jpg'),
('Fried Rice', 'Stir-fry rice with vegetables and soy sauce.', '/images/fried_rice.jpg'),
('Tomato Soup', 'Cook tomatoes with broth and blend.', '/images/tomato_soup.jpg');

-- Inserting into the MealIngredients table
INSERT INTO MealIngredients (MealID, IngredientID, Quantity) VALUES
((SELECT MealID FROM Meals WHERE MealName = 'Chocolate Cake'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Flour'), '2 Cups'),
((SELECT MealID FROM Meals WHERE MealName = 'Chocolate Cake'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Sugar'), '1 Cup'),
((SELECT MealID FROM Meals WHERE MealName = 'Chocolate Cake'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Eggs'), '3 Pieces'),
((SELECT MealID FROM Meals WHERE MealName = 'Spaghetti Carbonara'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Pasta'), '200 Grams'),
((SELECT MealID FROM Meals WHERE MealName = 'Spaghetti Carbonara'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Bacon'), '100 Grams'),
((SELECT MealID FROM Meals WHERE MealName = 'Spaghetti Carbonara'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Cheese'), '1 Cup'),
((SELECT MealID FROM Meals WHERE MealName = 'Caesar Salad'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Lettuce'), '5 Leaves'),
((SELECT MealID FROM Meals WHERE MealName = 'Grilled Chicken'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Chicken Breast'), '2 Pieces'),
((SELECT MealID FROM Meals WHERE MealName = 'Grilled Chicken'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Salt'), '1 Teaspoon'),
((SELECT MealID FROM Meals WHERE MealName = 'Grilled Chicken'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Pepper'), '1 Teaspoon'),
((SELECT MealID FROM Meals WHERE MealName = 'Beef Stew'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Beef'), '1 Pound'),
((SELECT MealID FROM Meals WHERE MealName = 'Beef Stew'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Onion'), '1 Piece'),
((SELECT MealID FROM Meals WHERE MealName = 'Beef Stew'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Salt'), '1 Teaspoon'),
((SELECT MealID FROM Meals WHERE MealName = 'Garlic Bread'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Bread'), '4 Slices'),
((SELECT MealID FROM Meals WHERE MealName = 'Garlic Bread'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Butter'), '2 Tablespoons'),
((SELECT MealID FROM Meals WHERE MealName = 'Garlic Bread'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Garlic'), '2 Cloves'),
((SELECT MealID FROM Meals WHERE MealName = 'Chicken Alfredo'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Pasta'), '200 Grams'),
((SELECT MealID FROM Meals WHERE MealName = 'Chicken Alfredo'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Tomato Sauce'), '1 Cup'),
((SELECT MealID FROM Meals WHERE MealName = 'Chicken Alfredo'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Chicken Breast'), '1 Piece'),
((SELECT MealID FROM Meals WHERE MealName = 'BLT Sandwich'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Bacon'), '4 Strips'),
((SELECT MealID FROM Meals WHERE MealName = 'BLT Sandwich'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Lettuce'), '3 Leaves'),
((SELECT MealID FROM Meals WHERE MealName = 'BLT Sandwich'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Mayonnaise'), '2 Tablespoons'),
((SELECT MealID FROM Meals WHERE MealName = 'Fried Rice'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Rice'), '2 Cups'),
((SELECT MealID FROM Meals WHERE MealName = 'Fried Rice'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Garlic'), '2 Cloves'),
((SELECT MealID FROM Meals WHERE MealName = 'Fried Rice'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Pepper'), '1 Teaspoon'),
((SELECT MealID FROM Meals WHERE MealName = 'Tomato Soup'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Tomato Sauce'), '4 Cups'),
((SELECT MealID FROM Meals WHERE MealName = 'Tomato Soup'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Onion'), '1 Piece'),
((SELECT MealID FROM Meals WHERE MealName = 'Tomato Soup'), (SELECT IngredientID FROM Ingredients WHERE IngredientName = 'Salt'), '1 Teaspoon');
